
11:44:11
::1

NTSchool\Phpblog\Core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/app/Model/Users.php:76
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/app/Core/User.php(42): NTSchool\Phpblog\Model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/app/Controller/UserController.php(42): NTSchool\Phpblog\Core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/app/Core/Core.php(41): NTSchool\Phpblog\Controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(4): NTSchool\Phpblog\Core\Core->run()
#4 {main}
-------------------------------------------------------------------------------------

11:44:11
::1

NTSchool\Phpblog\Core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/app/Model/Users.php:76
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/app/Core/User.php(42): NTSchool\Phpblog\Model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/app/Controller/UserController.php(42): NTSchool\Phpblog\Core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/app/Core/Core.php(41): NTSchool\Phpblog\Controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(4): NTSchool\Phpblog\Core\Core->run()
#4 {main}
-------------------------------------------------------------------------------------
