
08:01:01
::1

NTSchool\Phpblog\Core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/app/Model/Users.php:113
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/app/Core/User.php(93): NTSchool\Phpblog\Model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/app/Controller/UserController.php(56): NTSchool\Phpblog\Core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/app/Application.php(94): NTSchool\Phpblog\Controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(6): NTSchool\Phpblog\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

08:01:01
::1

NTSchool\Phpblog\Core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/app/Model/Users.php:113
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/app/Core/User.php(93): NTSchool\Phpblog\Model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/app/Controller/UserController.php(56): NTSchool\Phpblog\Core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/app/Application.php(94): NTSchool\Phpblog\Controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(6): NTSchool\Phpblog\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

08:01:01
::1

NTSchool\Phpblog\Core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/app/Model/Users.php:113
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/app/Core/User.php(93): NTSchool\Phpblog\Model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/app/Controller/UserController.php(56): NTSchool\Phpblog\Core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/app/Application.php(94): NTSchool\Phpblog\Controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(6): NTSchool\Phpblog\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

08:01:01
::1

NTSchool\Phpblog\Core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/app/Model/Users.php:113
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/app/Core/User.php(93): NTSchool\Phpblog\Model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/app/Controller/UserController.php(56): NTSchool\Phpblog\Core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/app/Application.php(94): NTSchool\Phpblog\Controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(6): NTSchool\Phpblog\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

08:01:01
::1

NTSchool\Phpblog\Core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/app/Model/Users.php:113
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/app/Core/User.php(93): NTSchool\Phpblog\Model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/app/Controller/UserController.php(56): NTSchool\Phpblog\Core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/app/Application.php(94): NTSchool\Phpblog\Controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(6): NTSchool\Phpblog\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

08:01:01
::1

NTSchool\Phpblog\Core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/app/Model/Users.php:103
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/app/Core/User.php(93): NTSchool\Phpblog\Model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/app/Controller/UserController.php(56): NTSchool\Phpblog\Core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/app/Application.php(94): NTSchool\Phpblog\Controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(6): NTSchool\Phpblog\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

08:02:01
::1

NTSchool\Phpblog\Core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/app/Model/Users.php:113
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/app/Core/User.php(93): NTSchool\Phpblog\Model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/app/Controller/UserController.php(56): NTSchool\Phpblog\Core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/app/Application.php(94): NTSchool\Phpblog\Controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(6): NTSchool\Phpblog\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

08:02:01
::1

NTSchool\Phpblog\Core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/app/Model/Users.php:113
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/app/Core/User.php(93): NTSchool\Phpblog\Model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/app/Controller/UserController.php(56): NTSchool\Phpblog\Core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/app/Application.php(94): NTSchool\Phpblog\Controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(6): NTSchool\Phpblog\Application->run()
#4 {main}
-------------------------------------------------------------------------------------
